# stdlib imports

# core django imports
from django.db import models
from django.contrib.auth.models import User

# 3rd party app imports
from localflavor.us.us_states import STATE_CHOICES
from model_utils.models import TimeStampedModel


class Position(TimeStampedModel):
	'''describe a user's job position'''
	position 			= models.CharField(max_length=30)
	
	# used in admin interface, shell, etc.; self.id value auto-generated by django
	def __unicode__(self):
		#return self.firstName or str(self.id)
		return "%s " %(self.position)

def upload_profilepic_to(instance, filename, created):
	return "profiles/%s/%s/%s" %(instance.user.user.user_id, filename, created) 

class UserProfile(TimeStampedModel):
	'''extends User object and contains secured personal and public info; extends User object'''
	
	# associate with django built-in objects
	user 				= models.OneToOneField(User)
	userpic				= models.ImageField('UserProfile', max_length=250,upload_to=upload_profilepic_to, null=True, blank=True)

	# activate a user account
	activation_key 		= models.CharField(max_length=40)
	key_expires 		= models.DateTimeField(null=True)
	
	# secured private personal data; 
	address1 			= models.CharField(max_length=200, blank=True)
	address2 			= models.CharField(max_length=200, blank=True)
	city 				= models.CharField(max_length=100, blank=True)
	state 				= models.CharField(max_length=2, choices=STATE_CHOICES, blank=True)
	zipcode 			= models.CharField(max_length=40, blank=True)
	website				= models.URLField(null=True, blank=True)
	
	# relation fields
	position 			= models.ForeignKey(Position)
	
	# used in admin interface, shell, etc.; self.id value autocreated by django
	def __unicode__(self):
		return self.user.username
